plugin: aws_ec2
regions:
  - ap-northeast-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Application
    prefix: tag_Name_
    separator: ""

# Priority of inventory_hostname
hostnames:
  - tag:Name
  - ip-address # Public IPv4
  - private-ip-address

compose:
  # Changing ansible_host without changing inventory_hostname
  # If you want to connect to the host with a private IPv4 address
  ansible_host: private_ip_address
  # If you want to connect to the host with SSM Session Manager
  # ansible_host: instance_id
