version: '3.2'
services:
  ansible:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USERNAME: ansible
    image: vscode-ansible
    init: true
    environment:
      - TZ=JST-9
      - LESSCHARSET=utf-8  # Prevent garbled characters. e.g. git log, less
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # for docker in docker(dind)
      - $HOME/.ssh:/home/ansible/.ssh:ro
      - ~/.aws:/home/ansible/.aws:ro
      - ..:/home/ansible/workspace:cached
    entrypoint: /usr/local/bin/entrypoint.sh
    command: sleep infinity
