name: "Ansible Lint"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint Ansible Playbooks
        uses: reviewdog/action-ansiblelint@8bb20b42133697620fab9651f44661a24923308a # v1.4.0
        with:
          github_token: ${{ secrets.github_token }}
          ansiblelint_version: 5.0.7
          reporter: github-pr-review # Change reporter.
          ansiblelint_flags: "-p launch_* dynamic_* roles"
          fail_on_error: true
